BACKEND=llamacpp
INSTANCES=1
CORES_PER_INSTANCE=32
CORE_START=32
NUMA_NODE=1
BASE_PORT=8080
PARALLEL=1
SLOT_CTX=8192
WEIGHTS=""
LLAMA_SERVER=/proj/rdi/staff/sacsharm/llama.cpp/build_zendnn/bin/llama-server
LLAMA_MODEL=/tmp/models/Llama-3.1-8B-Instruct-Q8_0.gguf
LOAD_MODE=mmap
