BACKEND=llamacpp
INSTANCES=8
CORES_PER_INSTANCE=4
CORE_START=224
NUMA_NODE=7
BASE_PORT=8080
PARALLEL=16
SLOT_CTX=2048
WEIGHTS=""
LLAMA_SERVER=/proj/rdi/staff/sacsharm/llama.cpp/build_zendnn/bin/llama-server
LLAMA_MODEL=/tmp/models/Llama-3.1-8B-Instruct-BF16.gguf
LOAD_MODE=mmap
