BACKEND=vllm
INSTANCES=1
CORES_PER_INSTANCE=32
CORE_START=128
NUMA_NODE=4
BASE_PORT=8000
PARALLEL=1
SLOT_CTX=4096
WEIGHTS=""
VLLM_BIN=/proj/rdi/staff/sacsharm/vllm/.venv/bin/vllm
VLLM_MODEL=/tmp/models/Meta-Llama-3.1-8B-Instruct-quantized.w8a8
SERVED_MODEL_NAME=llama31-8b-w8a8
KVCACHE_SPACE_GB=16
ENFORCE_EAGER=0
