#!/usr/bin/env bash
# Generate an HAProxy weighted-round-robin config from the manifest written by
# start_servers.sh on the inference pod, then start HAProxy here (runs ON the
# support pod, turin-xcovoid0021-pod-5).
#
# HAProxy lives on the support pod on purpose: the inference pod's 32 cores
# stay 100% dedicated to the server instances. The manifest travels between
# pods over the shared /proj filesystem.
#
#   ./start_haproxy.sh llamacpp_2x16
#   ./start_haproxy.sh llamacpp_2x16 --port 9000 --stats-port 9001
#
# HAProxy's "balance roundrobin" is a *dynamic weighted* round robin: each
# server is selected in proportion to its `weight`, which start_servers.sh sets
# to the instance's core count. Equal-sized instances therefore get equal
# share; a heterogeneous layout (e.g. 16+8+8 cores) splits 50/25/25.
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

CONFIG_NAME="${1:-}"
FE_PORT=9000
STATS_PORT=9001
shift || true
while [ $# -gt 0 ]; do
  case "$1" in
    --port)       FE_PORT="$2"; shift 2 ;;
    --stats-port) STATS_PORT="$2"; shift 2 ;;
    *) echo "unknown arg: $1" >&2; exit 1 ;;
  esac
done

if [ -z "$CONFIG_NAME" ]; then
  echo "usage: $0 <config-name> [--port 9000] [--stats-port 9001]" >&2
  echo "available manifests:" >&2
  ls -d "$SCRIPT_DIR"/run/*/ 2>/dev/null | xargs -rn1 basename | sed 's/^/  /' >&2
  exit 1
fi

CONFIG_NAME="$(basename "$CONFIG_NAME" .conf)"
RUN_DIR="$SCRIPT_DIR/run/$CONFIG_NAME"
MANIFEST="$RUN_DIR/manifest.json"
LB_DIR="$RUN_DIR/lb"
CFG="$LB_DIR/haproxy.cfg"
LOG="$LB_DIR/haproxy.log"
PIDFILE="$LB_DIR/haproxy.pid"

if [ ! -f "$MANIFEST" ]; then
  echo "manifest not found: $MANIFEST" >&2
  echo "run start_servers.sh on the inference pod first." >&2
  exit 1
fi

mkdir -p "$LB_DIR"

# stop a previous instance of *our* haproxy, if any
if [ -f "$PIDFILE" ]; then
  oldpid="$(cat "$PIDFILE" 2>/dev/null)"
  if [ -n "$oldpid" ] && kill -0 "$oldpid" 2>/dev/null; then
    echo "stopping previous haproxy (pid $oldpid)"
    kill -TERM "$oldpid" 2>/dev/null
    sleep 2
  fi
  rm -f "$PIDFILE"
fi

# ------------------------------------------------------------ generate cfg --
python3 - "$MANIFEST" "$CFG" "$FE_PORT" "$STATS_PORT" "$LB_DIR" <<'PY'
import json, sys

manifest, out, fe_port, stats_port, lb_dir = sys.argv[1:6]
m = json.load(open(manifest))
host = m["host"]

lines = [
    "# generated by start_haproxy.sh -- do not edit by hand",
    f"# config={m['config_name']} backend={m['backend']} pod={m['pod']}",
    "",
    "global",
    "    maxconn 8192",
    "    nbthread 4",
    f"    stats socket {lb_dir}/haproxy.sock mode 660 level admin",
    "",
    "defaults",
    "    mode http",
    "    option httplog",
    # Without http-no-delay HAProxy may coalesce small SSE frames, which would
    # inflate the measured TTFT/TPOT. Mandatory for token-streaming workloads.
    "    option http-no-delay",
    "    timeout connect 10s",
    "    timeout client  900s",
    "    timeout server  900s",
    "    timeout tunnel  900s",
    "    retries 0",
    "",
    "frontend fe_llm",
    f"    bind *:{fe_port}",
    "    default_backend be_llm",
    "",
    "backend be_llm",
    "    # dynamic weighted round robin -- weight == instance core count",
    "    balance roundrobin",
    "    option httpchk",
    "    http-check send meth GET uri /health",
    "    http-check expect status 200",
    "    # lets the client confirm which instance actually served each request",
    "    http-response set-header X-Served-By %[srv_name]",
]
for inst in m["instances"]:
    lines.append(
        f"    server inst{inst['idx']} {host}:{inst['port']} "
        f"weight {inst['weight']} check inter 5s fall 3 rise 2 maxconn 512"
        f"   # cores {inst['cores']}"
    )

lines += [
    "",
    "listen stats",
    f"    bind *:{stats_port}",
    "    stats enable",
    "    stats uri /",
    "    stats refresh 5s",
    "",
]
open(out, "w").write("\n".join(lines) + "\n")
total = sum(i["weight"] for i in m["instances"])
print(f"backends ({len(m['instances'])}):")
for i in m["instances"]:
    print(f"  inst{i['idx']}  {host}:{i['port']}  cores {i['cores']:>8}  "
          f"weight {i['weight']:>3}  -> {100.0*i['weight']/total:.1f}% of traffic")
PY
[ $? -eq 0 ] || exit 1

# ----------------------------------------------------------------- launch --
if ! haproxy -c -f "$CFG" >/dev/null 2>"$LB_DIR/check.err"; then
  echo "haproxy config check FAILED:" >&2
  cat "$LB_DIR/check.err" >&2
  exit 1
fi

setsid nohup haproxy -f "$CFG" > "$LOG" 2>&1 < /dev/null &
HAPID=$!
echo "$HAPID" > "$PIDFILE"

for _ in $(seq 1 20); do
  if (exec 3<>"/dev/tcp/127.0.0.1/$FE_PORT") 2>/dev/null; then exec 3<&-; break; fi
  sleep 0.5
done

if ! (exec 3<>"/dev/tcp/127.0.0.1/$FE_PORT") 2>/dev/null; then
  echo "haproxy did not come up on :$FE_PORT -- log:" >&2
  tail -20 "$LOG" >&2
  exit 1
fi
exec 3<&- 2>/dev/null

echo
echo "haproxy up (pid $HAPID)"
echo "  config : $CFG"
echo "  log    : $LOG"
echo "  proxy  : http://127.0.0.1:${FE_PORT}"
echo "  stats  : http://127.0.0.1:${STATS_PORT}/"

# end-to-end smoke test through the LB
BK="$(python3 -c "import json;print(json.load(open('$MANIFEST'))['backend'])")"
if [ "$BK" = "llamacpp" ]; then
  probe="$(curl -s --max-time 30 -H 'Content-Type: application/json' -D /tmp/hdr.$$ \
    -d '{"prompt":[1,2,3],"n_predict":1,"stream":false,"cache_prompt":false}' \
    "http://127.0.0.1:${FE_PORT}/completion")"
else
  MDL="$(python3 -c "import json;print(json.load(open('$MANIFEST'))['served_model_name'])")"
  probe="$(curl -s --max-time 60 -H 'Content-Type: application/json' -D /tmp/hdr.$$ \
    -d "{\"model\":\"$MDL\",\"prompt\":[1,2,3],\"max_tokens\":1}" \
    "http://127.0.0.1:${FE_PORT}/v1/completions")"
fi
if [ -n "$probe" ]; then
  echo "  smoke  : OK (served by $(grep -i '^x-served-by:' /tmp/hdr.$$ | tr -d '\r' | awk '{print $2}'))"
else
  echo "  smoke  : FAILED -- backends may not be reachable from this pod" >&2
fi
rm -f /tmp/hdr.$$
exit 0
